package interfaces;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import ufpbook.*;

public class PnlPost extends javax.swing.JPanel implements Serializable {

    private Postagem post;
    private Usuario user;
    private SubTelaMural mural;
    
    public PnlPost(SubTelaMural mural, Postagem post, Usuario user) {
        initComponents();
        
        this.post = post;
        this.user = user;
        this.mural = mural;
        
        lblAutor.setText(post.getAutor().getNome());
        txtTexto.setText(post.getTexto());
        
        if(post.getImagem() != null) {
            ImageIcon imagem = new ImageIcon(post.getImagem().getPath());
            imagem.setImage(imagem.getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
            lblImagemPost.setIcon(imagem);
            lblImagemPost.addMouseListener(new MouseAdapter(){
                    public void mouseClicked(MouseEvent e){
                       JFrame frame = new JFrame();
                       ImageIcon img2 = new ImageIcon(post.getImagem().getPath());
                       img2.setImage(img2.getImage().getScaledInstance(800, 800, Image.SCALE_SMOOTH));
                       JLabel lbl = new JLabel(img2);
                       frame.add(lbl);
                       frame.setSize(800, 800);
                       frame.setLocationRelativeTo(null);
                       frame.setVisible(true);
                    }
                    public void mouseEntered(MouseEvent e) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                    }

                    public void mouseExited(MouseEvent e) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    }
                });
        }
        
        scrollComents.setVisible(false);
        
        if(user.equals(post.getAutor()) || mural.getMural().getAdmins().contains(user)) {
            btnDelPost.setVisible(true);
        } else {
            btnDelPost.setVisible(false);
        }
        
        loadComentarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComentarios = new javax.swing.JButton();
        lblAutor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        lblImagemPost = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();
        txtFazerComent = new javax.swing.JTextField();
        scrollComents = new javax.swing.JScrollPane();
        pnlComents = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDelPost = new javax.swing.JButton();

        btnComentarios.setText("Comentários");
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });

        lblAutor.setText("Autor");

        txtTexto.setEditable(false);
        txtTexto.setColumns(20);
        txtTexto.setRows(3);
        jScrollPane2.setViewportView(txtTexto);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        txtFazerComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFazerComentActionPerformed(evt);
            }
        });

        pnlComents.setLayout(new javax.swing.BoxLayout(pnlComents, javax.swing.BoxLayout.Y_AXIS));
        scrollComents.setViewportView(pnlComents);

        btnDelPost.setText("Deletar Postagem");
        btnDelPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFazerComent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImagemPost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelPost))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComentarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComentar))))
                    .addComponent(scrollComents))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutor)
                            .addComponent(btnDelPost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComentarios)
                            .addComponent(btnComentar)))
                    .addComponent(lblImagemPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFazerComent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollComents, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        boolean visivel = scrollComents.isVisible();
        scrollComents.setVisible(!visivel);
        revalidate();
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
            if(!txtFazerComent.getText().equals("")) {
                Comentario coment = new Comentario(user, txtFazerComent.getText());
                post.addComentario(coment);
                pnlComents.add(new PnlComentario(user,post, coment, this));
                pnlComents.revalidate();
            }
            
            scrollComents.setVisible(true);
            revalidate();
    }//GEN-LAST:event_btnComentarActionPerformed

    private void txtFazerComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFazerComentActionPerformed
        btnComentar.doClick();
    }//GEN-LAST:event_txtFazerComentActionPerformed

    private void btnDelPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPostActionPerformed
        mural.getDono().getMural().getPostagens().remove(post);
        mural.loadPostagens();
    }//GEN-LAST:event_btnDelPostActionPerformed

    public void loadComentarios() {
        pnlComents.removeAll();
        for(Comentario comentario : post.getComentarios()) {
            pnlComents.add(new PnlComentario(user,post, comentario, this));
        }
        pnlComents.revalidate();
    }
    
    public Mural getTelaPai() {
        return mural.getDono().getMural();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btnDelPost;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblImagemPost;
    private javax.swing.JPanel pnlComents;
    private javax.swing.JScrollPane scrollComents;
    private javax.swing.JTextField txtFazerComent;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
