package interfaces;

import ufpbook.*;

public class SubTelaGrupos extends javax.swing.JPanel {

    private RedeSocial redesocial;
    private TelaUsuario telausuario;
    
    public SubTelaGrupos(RedeSocial redesocial,TelaUsuario telausuario) {
        initComponents();
        
        this.redesocial = redesocial;
        this.telausuario = telausuario;
      
        estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmMenuNovoGrupo = new javax.swing.JFrame();
        btnFinalizar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();
        pnlGrupos = new javax.swing.JPanel();
        lblGrupos = new javax.swing.JLabel();
        txtProcurarG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlConteudoG = new javax.swing.JPanel();
        pnlProcurar = new javax.swing.JPanel();
        lblProcurar = new javax.swing.JLabel();
        txtPrucurarP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlConteudoP = new javax.swing.JPanel();
        btnCriarGrupo = new javax.swing.JButton();

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome do grupo:");

        javax.swing.GroupLayout frmMenuNovoGrupoLayout = new javax.swing.GroupLayout(frmMenuNovoGrupo.getContentPane());
        frmMenuNovoGrupo.getContentPane().setLayout(frmMenuNovoGrupoLayout);
        frmMenuNovoGrupoLayout.setHorizontalGroup(
            frmMenuNovoGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmMenuNovoGrupoLayout.createSequentialGroup()
                .addGroup(frmMenuNovoGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmMenuNovoGrupoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnFinalizar))
                    .addGroup(frmMenuNovoGrupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNome))
                    .addGroup(frmMenuNovoGrupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmMenuNovoGrupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        frmMenuNovoGrupoLayout.setVerticalGroup(
            frmMenuNovoGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmMenuNovoGrupoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );

        lblGrupos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGrupos.setText("Seus Grupos:");

        txtProcurarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarGActionPerformed(evt);
            }
        });

        pnlConteudoG.setLayout(new javax.swing.BoxLayout(pnlConteudoG, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlConteudoG);

        javax.swing.GroupLayout pnlGruposLayout = new javax.swing.GroupLayout(pnlGrupos);
        pnlGrupos.setLayout(pnlGruposLayout);
        pnlGruposLayout.setHorizontalGroup(
            pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlGruposLayout.createSequentialGroup()
                        .addGroup(pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProcurarG, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlGruposLayout.setVerticalGroup(
            pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProcurarG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        lblProcurar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProcurar.setText("Procure Novos Grupos:");

        txtPrucurarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrucurarPActionPerformed(evt);
            }
        });

        pnlConteudoP.setLayout(new javax.swing.BoxLayout(pnlConteudoP, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pnlConteudoP);

        javax.swing.GroupLayout pnlProcurarLayout = new javax.swing.GroupLayout(pnlProcurar);
        pnlProcurar.setLayout(pnlProcurarLayout);
        pnlProcurarLayout.setHorizontalGroup(
            pnlProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcurarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProcurarLayout.createSequentialGroup()
                        .addGroup(pnlProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrucurarP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProcurar))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcurarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        pnlProcurarLayout.setVerticalGroup(
            pnlProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcurarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProcurar)
                .addGap(11, 11, 11)
                .addComponent(txtPrucurarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCriarGrupo.setText("Criar grupo");
        btnCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCriarGrupo))
                    .addComponent(pnlProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriarGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(pnlProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarGActionPerformed
        pnlConteudoG.removeAll();
        for (String nome  : redesocial.getGrupos().keySet()) {
            Grupo grupo = redesocial.getGrupo(nome);
            if(grupo.getPessoas().contains(telausuario.getUser()) && nome.startsWith(txtProcurarG.getText())) {
                pnlConteudoG.add( new PnlGrupo(telausuario, this, grupo, true));
            }
        }
        pnlConteudoG.revalidate();
    }//GEN-LAST:event_txtProcurarGActionPerformed

    private void txtPrucurarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrucurarPActionPerformed
        pnlConteudoP.removeAll();
        for(String nome  : redesocial.getGrupos().keySet()) {
            Grupo grp = redesocial.getGrupos().get(nome);
            if(nome.startsWith(txtPrucurarP.getText()) &&
                    !grp.getPessoas().contains(telausuario.getUser()) &&
                    !grp.getBloqueados().contains(telausuario.getUser())) {
                pnlConteudoP.add(new PnlGrupo(telausuario,this,grp, false));
            }  
        }
        pnlConteudoP.revalidate();
    }//GEN-LAST:event_txtPrucurarPActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if(redesocial.registroGrupo(telausuario.getUser(), txtNome.getText())) {
                pnlConteudoG.revalidate();
                frmMenuNovoGrupo.setVisible(false);
                txtNome.setText(null);
                lblErro.setText(null);
                estadoInicial();
                pnlConteudoG.revalidate();
            } else {
                lblErro.setText("Nome inválido!");
            }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGrupoActionPerformed
        frmMenuNovoGrupo.setSize(400, 170);
        frmMenuNovoGrupo.setLocationRelativeTo(null);
        frmMenuNovoGrupo.setVisible(true);
    }//GEN-LAST:event_btnCriarGrupoActionPerformed

    public void estadoInicial(){
        pnlConteudoG.removeAll();
        pnlConteudoP.removeAll();
        for (String nome  : redesocial.getGrupos().keySet()) {
            Grupo grupo = redesocial.getGrupo(nome);
            if(grupo.getPessoas().contains(telausuario.getUser())) {
                pnlConteudoG.add( new PnlGrupo(telausuario, this, grupo, true));
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarGrupo;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JFrame frmMenuNovoGrupo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProcurar;
    private javax.swing.JPanel pnlConteudoG;
    private javax.swing.JPanel pnlConteudoP;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JPanel pnlProcurar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProcurarG;
    private javax.swing.JTextField txtPrucurarP;
    // End of variables declaration//GEN-END:variables
}
