package interfaces;

import java.awt.CardLayout;
import javax.swing.JPanel;
import ufpbook.*;

public class TelaUsuario extends javax.swing.JPanel {

    private RedeSocial redesocial;
    private Usuario user;
    private SubTelaAmigos subTelaAmigos;
    private SubTelaSolicitacoes subTelaSolicitacoes;
    private SubTelaGrupos subTelaGrupos;
    private SubTelaFotos subTelaFotos;
    private SubTelaPerfil subTelaPerfil;
    private SubTelaMural subTelaMural;
    
    public TelaUsuario(RedeSocial redesocial, Usuario user) {
        initComponents();
        
        this.redesocial = redesocial;
        this.user = user;
      
        btnMural.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlMenuLateral = new javax.swing.JPanel();
        btnAmigos = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnFotos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnMural = new javax.swing.JButton();
        btnSolicitacoes = new javax.swing.JButton();
        pnlConteudo = new javax.swing.JPanel();

        btnAmigos.setText("Amigos");
        btnAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmigosActionPerformed(evt);
            }
        });

        btnGrupos.setText("Grupos");
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        btnFotos.setText("Minhas Fotos");
        btnFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotosActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnMural.setText("Mural");
        btnMural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuralActionPerformed(evt);
            }
        });

        btnSolicitacoes.setText("Solicitações");
        btnSolicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLateralLayout = new javax.swing.GroupLayout(pnlMenuLateral);
        pnlMenuLateral.setLayout(pnlMenuLateralLayout);
        pnlMenuLateralLayout.setHorizontalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMural, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLateralLayout.setVerticalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAmigos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFotos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(btnMural)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(pnlMenuLateral);

        pnlConteudo.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(pnlConteudo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmigosActionPerformed
        if(subTelaAmigos == null){
            subTelaAmigos = new SubTelaAmigos(redesocial,this);
            pnlConteudo.add("Amigos", subTelaAmigos);
        } else{
            subTelaAmigos.estadoInicial();
        }
        
        CardLayout layout = (CardLayout) pnlConteudo.getLayout();
        layout.show(pnlConteudo, "Amigos");
    }//GEN-LAST:event_btnAmigosActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        if(subTelaGrupos == null){
            subTelaGrupos = new SubTelaGrupos(redesocial,this);
            pnlConteudo.add("Grupos", subTelaGrupos);
        } else{
            subTelaGrupos.estadoInicial();
        }
        
        CardLayout layout = (CardLayout) pnlConteudo.getLayout();
        layout.show(pnlConteudo, "Grupos");
    }//GEN-LAST:event_btnGruposActionPerformed

    private void btnFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotosActionPerformed
        if(subTelaFotos == null){
           subTelaFotos = new SubTelaFotos(user);
           pnlConteudo.add("Fotos", subTelaFotos);
        } else{
            subTelaFotos.estadoInicial();
        }
        
        CardLayout layout = (CardLayout)pnlConteudo.getLayout();
        layout.show(pnlConteudo, "Fotos");
    }//GEN-LAST:event_btnFotosActionPerformed

    private void btnMuralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuralActionPerformed
        if(subTelaMural == null){
            subTelaMural = new SubTelaMural(this, user);
            pnlConteudo.add("Mural", subTelaMural);
        } else{
            subTelaMural.loadPostagens();
        }
        
        CardLayout layout = (CardLayout) pnlConteudo.getLayout();
        layout.show(pnlConteudo, "Mural");
    }//GEN-LAST:event_btnMuralActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        if(subTelaPerfil == null){
           pnlConteudo.add("Perfil", new SubTelaPerfil(redesocial, user));
        }
        
        CardLayout layout = (CardLayout) pnlConteudo.getLayout();
        layout.show(pnlConteudo, "Perfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        CardLayout layout = (CardLayout) TelaPrincipal.PainelPrincipal.getLayout();
        layout.show(TelaPrincipal.PainelPrincipal, "Login");
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitacoesActionPerformed
        if(subTelaSolicitacoes == null){
           pnlConteudo.add("solicitacoes", new SubTelaSolicitacoes(this));
        } else{
            subTelaSolicitacoes.estadoInicial();
        }
        
        CardLayout layout = (CardLayout) pnlConteudo.getLayout();
        layout.show(pnlConteudo, "solicitacoes");
    }//GEN-LAST:event_btnSolicitacoesActionPerformed
    
    public JPanel getPnlConteudo() {
        return pnlConteudo;
    }
    
    public Usuario getUser() {
        return user;
    }
    
    public RedeSocial getRede() {
        return redesocial;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmigos;
    private javax.swing.JButton btnFotos;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnMural;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSolicitacoes;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlConteudo;
    private javax.swing.JPanel pnlMenuLateral;
    // End of variables declaration//GEN-END:variables
}
